theme: jekyll-theme-minimal
title: Polirural Final Integration, Release & Licensing
description: Public Repositories
logo: https://raw.githubusercontent.com/polirural/.github/main/profile/logo_polirural.png
show_downloads: False
toc: true
